CREATE TABLE STATS (
                       STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
                       STAT_DATE DATETIME NOT NULL,
                       STAT VARCHAR(20) NOT NULL,
                       VALUE INT(11) NOT NULL);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT count(*) FROM BOOKS
WHERE BESTSELLER=1;

USE KODILLA_COURSE;
DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS
    ON SCHEDULE EVERY 1 MINUTE
    DO
    BEGIN
        DECLARE BESTSELLERS_VALUE INT(11) DEFAULT 0;
        CALL UpdateBestsellers();

        SELECT QTY INTO BESTSELLERS_VALUE FROM BESTSELLERS_COUNT WHERE QTY>0;

        INSERT INTO STATS (STAT_DATE, STAT, VALUE)
        VALUES (curdate(), "BESTSELLERS", BESTSELLERS_VALUE);
        COMMIT;
    END $$

DELIMITER ;

select * from STATS;

drop event UPDATE_BESTSELLERS;